DROP TABLE IF EXISTS HERO;
CREATE TABLE HERO (
  ID BIGINT PRIMARY KEY,
  NAME VARCHAR(255),
  DESCRIPTION VARCHAR(255)
);

DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
    ID BIGINT PRIMARY KEY,
    USERNAME VARCHAR(255),
    PASSWORD VARCHAR(255)
);
